vocab_size: 10000
d_model: 128  # 16, 32, 64, 128
rope_theta: 10000
n_heads: 1 
context_length: 16384 # 256, 1024, 4096, 8192, 16384
batch_size: 8
num_samples: 100
forward_only: true
mixed_precision: false
log_name: att