vocab_size: 10000
d_model: 2560  # 768 1280 2560
d_ff: 10240   # 3072 5120 10240
rope_theta: 10000
n_layers: 32  # 12 36 32
n_heads: 32  # 12 20 32
context_length: 128
batch_size: 4
num_samples: 5
forward_only: true
mixed_precision: false
use_jit: true
log_name: benchmark